name: "Build Docker Image and Push to GHCR"
author: "@GlueOps"
description: "Abstracts defining actions to push Docker images to desired registry, defaults to ghcr.io"
branding:
  icon: 'box'
  color: 'yellow'



inputs:
  # common inputs
  registry:
    description: 'The container registry to push the image to'
    required: true
    default: "ghcr.io"

  registry-username:
    description: 'The username for authentication to the container registry (defaults to the github.actor)'
    required: true
    default: ${{ github.actor }}

  image_name:
    description: 'Docker image is named after repository'
    required: true
    default: ${{ github.repository }} 

  context:
    description: "A path to the context in which the build will happen, see https://docs.docker.com/engine/reference/commandline/build/"
    required: false
    default: "."


  # ghcr
  github_token: 
     description: "Personal Access Token (PAT) used to authenticate with the GitHub Container Registry."
     required: false
     default: ${{ github.token }}


  # ecr
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: false

  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: false

  aws_default_region:
    description: 'AWS Default Region'
    required: false


  # docker hub
  dockerhub_username:
    description: 'Docker Hub Username'
    required: false

  dockerhub_password:
    description: 'Docker Hub Password or Token'
    required: false



runs:
  using: "composite"
  steps:
    - name: Configure for AWS if using ECR
      shell: bash
      if: contains(inputs.registry, '.dkr.ecr.')
      run: |
        echo "::group::Installing AWS CLI..."
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
        echo "::endgroup::"
        
        echo "::group::Setting AWS Credentials to Environment Variables"
        # set aws credentials as env vars
        if [[ -n "${{ inputs.aws_access_key_id }}" ]]; then
          echo "AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }}" >> $GITHUB_ENV
        fi
        if [[ -n "${{ inputs.aws_secret_access_key }}" ]]; then
          echo "AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}" >> $GITHUB_ENV
        fi
        if [[ -n "${{ inputs.aws_default_region }}" ]]; then
          echo "AWS_DEFAULT_REGION=${{ inputs.aws_default_region }}" >> $GITHUB_ENV
        fi
        echo "::endgroup::"

    # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry
    - name: Registry Authentication
      shell: bash
      run: |
        case "${{ inputs.registry }}" in
          "ghcr.io")
            echo "${{ inputs.github_token }}" | docker login ${{ inputs.registry }} -u ${{ github.actor }} --password-stdin
            ;;
          *".dkr.ecr."*)
            echo "$(aws ecr get-login-password)" | docker login --username AWS --password-stdin ${{ inputs.registry }}
            ;;
          "docker.io")
            echo "${{ inputs.dockerhub_password }}" | docker login -u "${{ inputs.dockerhub_username }}" --password-stdin
            ;;
          *)
            echo "Unsupported registry"
            exit 1
            ;;
        esac

    - name: Clone Respository and Build Container
      shell: bash
      env:
        DOCKER_BUILDKIT: '1'
        IMAGE_NAME: ${{ inputs.image_name }}

      run: |
        echo "::group::Cloning target ref..."
        # initial ref is branch
        export TARGET_REF="${GITHUB_REF#refs/heads/}"
        # if tag, replace branch with tag
        export TARGET_REF="${TARGET_REF#refs/tags/}"
        echo "Current ref is: $TARGET_REF"
      
        git clone --depth=1 --branch="$TARGET_REF" "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}" .
        echo "Using $(docker -v)"
        echo "::endgroup::"
        
        echo "::group::Set Tags"
        echo "Event payload: ${{ toJson(github.event_name) }}"

        # Clean up TARGET_REF for invalid characters
        TARGET_REF=${TARGET_REF////-}      # Replace slashes with hyphens
        TARGET_REF=${TARGET_REF//[^a-zA-Z0-9_.-]/_}   # Replace invalid characters with underscores
        TARGET_REF=${TARGET_REF// /_}      # Replace whitespaces with underscores
        TARGET_REF=${TARGET_REF,,}         # Convert to lowercase
        export TARGET_REF="$TARGET_REF"
        export SHA="${{ github.sha }}"
        export SHORT_SHA="${SHA:0:7}"

        echo "Target Ref: ${TARGET_REF}"
        echo "Short SHA: ${SHORT_SHA}"
        echo "Long SHA: ${SHA}"

        # convert the image name to lowercase
        export IMAGE_NAME=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
        echo "::endgroup::"

        export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        export GITHUB_URL=https://github.com/${{ github.repository }}

        echo "::group::Building the Docker image as ${{ inputs.registry }}/${IMAGE_NAME}:${TARGET_REF} from ${{ inputs.dockerfile }} in ${{ inputs.context }} context ..."
        docker build \
          --file "${{ inputs.dockerfile }}" \
          --cache-from "${{ inputs.registry }}/${IMAGE_NAME}:latest" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --build-arg BUILD_DATE="${BUILD_DATE}" \
          --build-arg GITHUB_SHA="${GITHUB_SHA}" \
          -t "${{ inputs.registry }}/${IMAGE_NAME}:${TARGET_REF}" \
          -t "${{ inputs.registry }}/${IMAGE_NAME}:${SHORT_SHA}" \
          -t "${{ inputs.registry }}/${IMAGE_NAME}:${SHA}" \
          --label "org.label-schema.build-date=${BUILD_DATE}" \
          --label "org.label-schema.vcs-url=${GITHUB_URL}" \
          --label "org.label-schema.vcs-ref=${GITHUB_SHA}" \
          --label "org.opencontainers.image.created=${BUILD_DATE}" \
          --label "org.opencontainers.image.source=${GITHUB_URL}" \
          --label "org.opencontainers.image.revision=${GITHUB_SHA}" \
          "${{ inputs.context }}"

        echo "::endgroup::"

        echo "::group::Inspecting the image ..."
        docker image ls

        echo "Labels:"
        docker image inspect "${{ inputs.registry }}/${IMAGE_NAME}:${TARGET_REF}" | jq '.[].Config.Labels'

        echo "Env variables:"
        docker image inspect "${{ inputs.registry }}/${IMAGE_NAME}:${TARGET_REF}" | jq '.[].Config.Env'

        echo "::endgroup::"

        echo "::group::Pushing the image to ${{ inputs.registry }} ..."
        docker push --all-tags "${{ inputs.registry }}/${IMAGE_NAME}" && echo "Pushed"
        echo "::endgroup::"
