####
## This is managed via terraform. Any changes to this file may be overridden by our automation
####

name: "auto-release"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-release:
    uses: GlueOps/github-workflows/.github/workflows/auto-release.yml@main
    secrets: inherit
